# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb2b381e974a7bd58737e73d0ede0f7119de32850367d1d6fe17372aaac318118c5f01483bf6162881182beb3e8237445e0edcc50ab9b083a0a7f8e60710a9ef

test:
  secret_key_base: 2a91e402c098f2a870c212112666cad6374e8a768ba5ed98160548b104cfa962ae4f32a356e4fb6c2f63c99adeb3f7839e2be9de38ba088b7d684ea063b94219

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
